[build]
  # Desativar warnings como erros durante o build no Netlify
  command = "CI=false craco build"
  functions = "netlify/functions"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configurações opcionais para Netlify Dev (modo de desenvolvimento local)
#[dev]
#  command = "yarn start" # Comando para iniciar o servidor de desenvolvimento
#  port = 3000 # Porta que o servidor de desenvolvimento estará escutando
#  publish = "dist" # Pasta com o conteúdo estático
